apiVersion: admin.gloo.solo.io/v2
kind: Workspace
metadata:
  name: gateways
  namespace: gloo-mesh
spec:
  workloadClusters:
    - name: test-ci-rs
      namespaces:
        - name: istio-gateways
    - name: sp-ci-rs
      namespaces:
        - name: istio-gateways
---
apiVersion: admin.gloo.solo.io/v2
kind: WorkspaceSettings
metadata:
  name: gateways
  namespace: istio-gateways
spec:
  importFrom:
    - workspaces:
        - selector:
            allow_ingress: "true"
      resources:
        - kind: SERVICE
        - kind: ALL
          labels:
            expose: "true"
  exportTo:
    - workspaces:
        - selector:
            allow_ingress: "true"
      resources:
        - kind: SERVICE