apiVersion: v1
kind: Service
metadata:
  name: gloo-mesh-ui-service
  namespace: gloo-mesh
  labels:
    app: gloo-mesh-ui
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8090
  selector:
    app: gloo-mesh-ui
  type: ClusterIP
